name: Maven Build

on: [ push, pull_request ]

jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v3

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 빌드 및 테스트 (maven verify)
        run: ./mvnw verify
